spring.application.name=confectionery
server.port=8080

spring.datasource.url=jdbc:postgresql://localhost:5432/confectionery_db
spring.datasource.username=postgres
spring.datasource.password=356MM!19I


spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true